### ISSUE TITLE
How to show only "name" itemprop property?

### ISSUE THREAD

**Issue by jurnalanas** [jcdarwin/microdata.reveal#1]
Hi, thanks for the nice work on this chrome extension, but I wonder how to show only "name" itemprop property instead of all the itemprop properties? I think it's somewhere on tmpl.microdata.js file, but I don't quite understand yet..

Thank you..

**Comment by jcdarwin** [comment]
Hi Muhammad,

Sorry for the delay in replying -- the quickest way would be to change line
79 in microdata.reveal.js:

var items = $('[itemscope]').not($('[itemscope] [itemscope]'));

You'll probably want to filter / iterate over this to only pick up the
items you want -- it's a jQuery selector, so refer to the jQuery docs, e.g.
http://api.jquery.com/filter/

Note that there is a memory leak in this extension, meaning that it works
well initially, but consumes more and more memory over time --
unfortunately I've not had the time to track it down and fix it.

Jason

**Comment by jurnalanas** [comment]
thank you.. :+1:
